name: Nightly Builds
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
jobs:
  ktb_docker_build:
    if: github.repository == 'kafka-ops/julie'
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: copy fat jar
        run: cp ./target/julie-ops.jar release/docker
      - name: copy runner file
        run: cp ./src/main/scripts/julie-ops-cli.sh release/docker
      - name: list files (release dir)
        run: ls -l
        working-directory: release/docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: release/docker
          file: release/docker/Dockerfile
          push: true
          tags: mobimeo/kafka-topology-builder:latest
  package_build:
    if: github.repository == 'kafka-ops/julie'
    name: Build rpm/deb packages (using maven)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build the rpm
        run: mvn rpm:rpm
      - uses: actions/upload-artifact@v2
        with:
          name: RPM package
          path: target/rpm/julie-ops/RPMS/noarch/*.rpm
      - uses: actions/upload-artifact@v2
        with:
          name: DEB package
          path: target/*.deb
      - uses: actions/upload-artifact@v2
        with:
          name: FAT jar
          path: target/julie-ops.jar
